defaults: &defaults
  twilio_account_sid: 'AC00a8989c9bb872af122b5ad9636b7347'
  twilio_auth_token: '9efbb468e830bac7a7582627e643222f'
  twilio_from: '+13183034399'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults